import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js';
import { getFirestore, collection, getDocs, doc, getDoc } from 'https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig), db=getFirestore(app); let allProps=[], current=null, imgIndex=0, timer=null;
const $=id=>document.getElementById(id);
async function load(){try{const s=await getDoc(doc(db,'settings','site')); if(s.exists()){const d=s.data(); if(d.marquee) $('marqueeText').textContent=d.marquee; if(d.brandName) $('brandName').textContent=d.brandName;} const cs=await getDocs(collection(db,'categories')); const cats=cs.docs.map(x=>({id:x.id,...x.data()})); renderCats(cats); const ps=await getDocs(collection(db,'properties')); allProps=ps.docs.map(x=>({id:x.id,...x.data()})); allProps.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)); fillFilter(cats); render(allProps);}catch(e){console.error('Firebase load failed:',e);$('properties').innerHTML=`<div class="empty">Could not load listings. ${esc(e.message||'Check Firebase setup, rules and network.')}</div>`}}
function renderCats(cats){$('categories').innerHTML='<button class="cat active" data-cat="all">All</button>'+cats.map(c=>`<button class="cat" data-cat="${esc(c.name)}">${esc(c.name)}</button>`).join(''); document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('filter').value=b.dataset.cat==='all'?'all':b.dataset.cat;render(b.dataset.cat==='all'?allProps:allProps.filter(p=>p.category===b.dataset.cat));});}
function fillFilter(cats){$('filter').innerHTML='<option value="all">All properties</option>'+cats.map(c=>`<option>${esc(c.name)}</option>`).join('');$('filter').onchange=e=>render(e.target.value==='all'?allProps:allProps.filter(p=>p.category===e.target.value));}
function render(items){if(!items.length){$('properties').innerHTML='<div class="empty">No properties added yet.</div>';return}$('properties').innerHTML=items.map(p=>`<article class="card" onclick="window.openProperty('${p.id}')"><div class="cardImg"><img src="${p.images?.[0]||''}"><span class="tag">${esc(p.category||'Property')}</span><span class="view">View photos</span></div><div class="cardBody"><h4>${esc(p.title)}</h4><div class="price">${esc(p.price||'Price on request')}</div><div class="location">📍 ${esc(p.location||'')}</div><p>${esc(p.description||'').slice(0,110)}${(p.description||'').length>110?'…':''}</p></div></article>`).join('')}
window.openProperty=id=>{current=allProps.find(p=>p.id===id);if(!current)return;imgIndex=0;showImg();$('modalTitle').textContent=current.title||'';$('modalTag').textContent=current.category||'Property';$('modalPrice').textContent=current.price||'Price on request';$('modalLocation').textContent='📍 '+(current.location||'');$('modalDesc').textContent=current.description||'';const phone=current.whatsapp||'';const msg=`Hello Nestora, I am interested in this property:\n\n${current.title||''}\nCategory: ${current.category||''}\nPrice: ${current.price||''}\nLocation: ${current.location||''}\n\nDescription:\n${current.description||''}`;$('waBtn').href=`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`;$('modal').classList.remove('hidden');startTimer();};
function showImg(){const imgs=current?.images||[];$('modalImg').src=imgs[imgIndex]||'';$('dots').innerHTML=imgs.map((_,i)=>`<i class="dot ${i===imgIndex?'on':''}"></i>`).join('');}
function next(n=1){const l=current?.images?.length||0;if(l){imgIndex=(imgIndex+n+l)%l;showImg();}}
function startTimer(){clearInterval(timer);timer=setInterval(()=>next(1),2000)}
$('next').onclick=()=>next(1);$('prev').onclick=()=>next(-1);$('closeModal').onclick=()=>{$('modal').classList.add('hidden');clearInterval(timer)};$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}load();
